receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"


processors:

  # Data sources: traces, metrics, logs
  batch:

  # Data sources: traces, metrics, logs
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

exporters:
  debug:
    verbosity: detailed

#  otlphttp:
#    traces_endpoint: http://backend-monitor-rastros:3000/trace/v1
#    encoding: json
#    compression: none
    
  #otlp/jaeger:
  #  endpoint: jeager_test:4317
  #  tls:
  #    insecure: true
      
  elasticsearch:
    endpoint: http://es-local-dev:9200
    auth:
      authenticator: basicauth
    mapping:
      mode: ecs
#    index: "traces-generic-default"
#   require_data_stream: false

extensions:
  basicauth:
    client_auth:
      username: elastic
      password: 31ESN3RZ

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
#      exporters: [debug,otlp/jaeger,otlphttp,elasticsearch]
      exporters: [debug,elasticsearch]