version: "3.5"
services:
 mysql-service-curso:
  container_name: mysql8_curso
  image: mysql:8.0
  restart: always
  networks:
   network_micro:
    ipv4_address: 192.168.1.10
  environment:
   MYSQL_ROOT_PASSWORD: cefetmg
   MYSQL_DATABASE: db_curso     
   MYSQL_USER: joaovitor
   MYSQL_PASSWORD: jvsd
  ports:
   - "3308:3306"
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcefetmg"]
    interval: 10s
    timeout: 5s
    retries: 3
 web-service-curso:
  container_name: springboot_curso
  build:
   context: ./cursocrud
   dockerfile: Dockerfile
  ports:
   - "8088:8080"
  networks:
   network_micro:
    ipv4_address: 192.168.1.20
  depends_on:
    mysql-service-curso:
      condition: service_healthy

 mysql-service-aluno:
  container_name: mysql8_aluno
  image: mysql:8.0
  restart: always
  networks:
   network_micro:
    ipv4_address: 192.168.1.30
  environment:
   MYSQL_ROOT_PASSWORD: cefetmg
   MYSQL_DATABASE: db_aluno     
   MYSQL_USER: joaovitor
   MYSQL_PASSWORD: jvsd
  ports:
   - "3307:3306"
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcefetmg"]
    interval: 10s
    timeout: 5s
    retries: 3
 web-service-aluno:
  container_name: springboot_aluno
  build:
   context: ./alunocrud
   dockerfile: Dockerfile
  ports:
   - "8087:8080"
  networks:
   network_micro:
    ipv4_address: 192.168.1.40
  depends_on:
    mysql-service-aluno:
      condition: service_healthy

 web-service-relatorio:
  container_name: springboot_relatorio
  build:
   context: ./relatorios
   dockerfile: Dockerfile
  ports:
   - "8089:8080"
  networks:
   network_micro:
    ipv4_address: 192.168.1.50
      
networks:
 network_micro:
  name: network_micro
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 192.168.1.0/24
