version: "3.5"
services:
 collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.116.1
    volumes:
      - ./collector-config.yaml:/collector-config.yaml
    command: ["--config=/collector-config.yaml"]
    expose:
      - "4318"
      - "4317"
    ports:
      - "4318:4318"
      - "4317:4317"
    networks:
     network_micro:
      ipv4_address: 192.168.1.60

 jeager_test:
    container_name: jeager_test
    image: jaegertracing/all-in-one:1.41
    environment: 
      COLLECTOR_OTLP_ENABLED: true
    expose:
      - "4318"
      - "4317"
      - "16686"
    ports:
      - "14318:4318"
      - "14317:4317"
      - "16686:16686"
    networks:
     network_micro:
      ipv4_address: 192.168.1.70
      
 mysql-service-curso:
  container_name: mysql-service-curso
  image: mysql:8.0
  restart: always
  networks:
   network_micro:
    ipv4_address: 192.168.1.10
  environment:
   MYSQL_ROOT_PASSWORD: cefetmg
   MYSQL_DATABASE: db_curso     
   MYSQL_USER: joaovitor
   MYSQL_PASSWORD: jvsd
  ports:
   - "3308:3306"
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcefetmg"]
    interval: 10s
    timeout: 5s
    retries: 3
 web-service-curso:
  container_name: web-service-curso
  build:
   context: ./cursocrud
   dockerfile: Dockerfile
  environment:
      OTEL_SERVICE_NAME: "web-service-curso"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://collector:4318/v1/traces"
      OTEL_JAVAAGENT_CONFIGURATION_FILE: "/config_agent.properties"
  ports:
   - "8088:8080"
  volumes:
   - ./sdk-config.yaml:/sdk-config.yaml
  networks:
   network_micro:
    ipv4_address: 192.168.1.20
  depends_on:
   mysql-service-curso:
    condition: service_healthy

 mysql-service-aluno:
  container_name: mysql-service-aluno
  image: mysql:8.0
  restart: always
  networks:
   network_micro:
    ipv4_address: 192.168.1.30
  environment:
   MYSQL_ROOT_PASSWORD: cefetmg
   MYSQL_DATABASE: db_aluno     
   MYSQL_USER: joaovitor
   MYSQL_PASSWORD: jvsd
  ports:
   - "3307:3306"
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcefetmg"]
    interval: 10s
    timeout: 5s
    retries: 3
    
 web-service-aluno:
  container_name: web-service-aluno
  build:
   context: ./alunocrud
   dockerfile: Dockerfile
  environment:
      OTEL_SERVICE_NAME: "web-service-aluno"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://collector:4318/v1/traces"
      OTEL_JAVAAGENT_CONFIGURATION_FILE: "/config_agent.properties"
  ports:
   - "8087:8080"
  volumes:
   - ./sdk-config.yaml:/sdk-config.yaml
  networks:
   network_micro:
    ipv4_address: 192.168.1.40
  depends_on:
    mysql-service-aluno:
      condition: service_healthy

 web-service-relatorio:
  container_name: web-service-relatorio
  build:
   context: ./relatorios
   dockerfile: Dockerfile
  environment:
      OTEL_SERVICE_NAME: "web-service-relatorio"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://collector:4318/v1/traces"
      OTEL_JAVAAGENT_CONFIGURATION_FILE: "/config_agent.properties"
  ports:
   - "8089:8080"
  volumes:
   - ./sdk-config.yaml:/sdk-config.yaml
  networks:
   network_micro:
    ipv4_address: 192.168.1.50
    
networks:
 network_micro:
  external: true
  name: network_micro
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 192.168.1.0/24
