receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
  mysql/aluno:
    endpoint: mysql-service-aluno:3306
    username: root
    password: cefetmg
    collection_interval: 60s
  
  mysql/curso:
    endpoint: mysql-service-curso:3306
    username: root
    password: cefetmg
    collection_interval: 60s

  hostmetrics:
    collection_interval: 1m
    root_path: /
    scrapers:
      memory: {}
      #cpu: {}
      #network: {}
      #load: {}
      #disk: {}
      #filesystem: {}

processors:

  # Data sources: traces, metrics, logs
  batch:

  # Data sources: traces, metrics, logs
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

exporters:
  debug:
    verbosity: detailed
    
  otlp/jaeger:
    endpoint: jeager_test:4317
    tls:
      insecure: true
      
  elasticsearch:
    endpoint: http://es-local-dev:9200
    auth:
      authenticator: basicauth
    mapping:
      mode: ecs
  zipkin:
    endpoint: http://zipkin_test:9411/api/v2/spans
  
  prometheusremotewrite:
    endpoint: http://prometheus_test:9090/api/v1/write
    tls:
       insecure: true


connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms,500ms,1s,2s,5s,10s]
    dimensions:
      - name: http.method
#        default: GET
      - name: http.status_code
      - name: host.name

    exemplars:
      enabled: true
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    metrics_flush_interval: 15s
    metrics_expiration: 5m
    events:
      enabled: true
      dimensions:
        - name: exception.type
        - name: exception.message
    resource_metrics_key_attributes:
      - service.name
      - telemetry.sdk.language
      - telemetry.sdk.name

extensions:
  basicauth:
    client_auth:
      username: elastic
      password: 31ESN3RZ

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
#      exporters: [debug,elasticsearch,otlp/jaeger,zipkin,]

#TESTE      exporters: [debug,elasticsearch, spanmetrics]
      exporters: [debug,elasticsearch]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug,elasticsearch]

    metrics:

#TESTE      receivers: [hostmetrics,otlp,spanmetrics,mysql/aluno,mysql/curso]
      receivers: [otlp]

#      processors: []
#      exporters: [debug,elasticsearch,prometheusremotewrite]
      exporters: [debug,elasticsearch]
