receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"


processors:

  # Data sources: traces, metrics, logs
  batch:

  # Data sources: traces, metrics, logs
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

exporters:
  debug:
    verbosity: detailed
    
  otlp/jaeger:
    endpoint: jeager_test:4317
    tls:
      insecure: true
      
  elasticsearch:
    endpoint: http://es-local-dev:9200
    auth:
      authenticator: basicauth
    mapping:
      mode: ecs
  
  zipkin:
    endpoint: http://zipkin_test:9411/api/v2/spans
  
  prometheusremotewrite:
    endpoint: http://prometheus_test:9090/api/v1/write
    tls:
       insecure: true

extensions:
  basicauth:
    client_auth:
      username: elastic
      password: 31ESN3RZ

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
      #exporters: [debug,elasticsearch,otlp/jaeger,zipkin,]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [elasticsearch]
      #exporters: [debug,elasticsearch]
      

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug,elasticsearch]
      #exporters: [debug,elasticsearch,prometheusremotewrite]
